# -*- coding: utf-8 -*-
"""intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GoxngTW5ZNuNGWJg6RhWk4YozNELKrq6
"""

num = 9
print(num)

import math
print(math.pow(num, 2))

_

/

##



"""Hello

*** head ***

**Hallo Colab**

```
<h1>Hello</h1>
```
"""



